### ISSUE TITLE
Error saving rules - Line 9: mismatched input '{' expecting {'function', 'service', 'syntax'}

### ISSUE THREAD

**Issue by grehce** [firebase/codelab-friendlychat-ios#12]
When the following block is added to Database rules, I get the Error listed in the title above. 

{
  "rules": {
        "messages": {
            ".read": "auth != null",
            ".write": "auth != null"
        }
  }
}

**Comment by morganchen12** [comment]
I'm able to publish this set of rules without issue.

```
{
  "rules": {
    "messages": {
    	".read": "auth != null",
    	".write": "auth != null"
    }
  }
}
```

Can you try again? If this fails persistently for you, please [file a bug through the Firebase support channel](https://firebase.google.com/support/contact/).

**Comment by samtstern** [comment]
The error "{'function', 'service', 'syntax'}" is a bit suspicious.  The rules here are for the Realtime Database, is it possible you're trying to deploy them as Cloud Firestore rules?

**Comment by grehce** [comment]
@samtstern, was led down Firestore beta feature and didn't even notice. Thanks, changed to realtime database and is working!

**Comment by grehce** [comment]
@samtstern thanks! So excited to get Google auth to work!!! 😄✨

**Comment by Sumirmat97** [comment]
> 
> 
> The error "{'function', 'service', 'syntax'}" is a bit suspicious. The rules here are for the Realtime Database, is it possible you're trying to deploy them as Cloud Firestore rules?

Thanks a lot. I was doing that.
